name: mailerlite
recipe: laravel
config:
  webroot: public
  via: nginx
  database: mysql
  php: '7.4'
  cache: redis
services:
  redis:
    type: redis
    portforward: 32859
  database:
    portforward: 32708
  node:
    type: node
    globals:
      laravel-echo-server: latest
    build:
      - npm install
tooling:
  npm:
    service: node
  node:
    service: node
  yarn:
    service: node
  phpunit:
    service: appserver
    description: "Run PHP Unit tests: lando phpunit"
    cmd: /app/vendor/bin/phpunit
    redis-cli:
      service: cache
proxy:
  node:
    - mailerlite.lndo.site:6001
